Implement preconnect to Google fonts
WordPress/twentyseventeen pull request #106
Opened 2016-09-28 16:09 UTC by leobaiano

Implements preconnect to google sources in accordance with issue #105

2016-09-28 16:18 UTC, grappler requested changes

2016-09-28 16:18 UTC, grappler commented on functions.php
> +
This is not related.

2016-09-28 16:18 UTC, grappler commented on functions.php
> +    // Add preconnect for Google Fonts if queue twentyfourteen-lato.
Please use tabs here instead of spaces.

2016-09-28 16:18 UTC, grappler commented on functions.php
> +	if ( wp_style_is( 'twentyseventeen_fonts_url', 'queue' ) && 'preconnect' === $relation_type )
We need the opening and closing brackets for the if statement.

2016-09-28 18:53 UTC, leobaiano commented on functions.php
> +
I had given space to create the function there, when I decided to change place forgot to delete the spaces, thanks for the warning.

2016-09-28 19:00 UTC, leobaiano commented on functions.php
> +
I removed the lines.

2016-09-28 19:00 UTC, leobaiano commented on functions.php
> +    // Add preconnect for Google Fonts if queue twentyfourteen-lato.
Done.

2016-09-28 19:00 UTC, leobaiano commented on functions.php
> +	if ( wp_style_is( 'twentyseventeen_fonts_url', 'queue' ) && 'preconnect' === $relation_type )
Done.

2016-09-28 20:01 UTC, swissspidy commented
Related: https://core.trac.wordpress.org/ticket/37171

2016-09-28 20:07 UTC, leobaiano commented
@swissspidy I pointed out that the issue want to open, see #105 😄

2016-10-19 15:27 UTC, davidakennedy commented
Refreshed in #491.

2016-10-19 15:27 UTC, closed without merging