Update style.css for Japanese Font. Issue #59
WordPress/twentyseventeen pull request #155
Opened 2016-10-06 11:26 UTC by nukaga

Update style.css for Japanese Font. Issue #59

2016-10-10 20:38 UTC, melchoyce commented
Hey, tested this out and it looks great.

@laurelfulford Do you have any preference where language-specific styles live in the stylesheet?

2016-10-10 21:01 UTC, laurelfulford commented
@melchoyce Adding them under the 'Typography' header makes sense to me! 

I think, if we add a lot of languages, it may be good to move the Genericons/icon font styles above them, but that's minor and we can cross that bridge when we get to it.

2016-10-10 21:02 UTC, melchoyce commented
> Adding them under the 'Typography' header makes sense to me!

Cool. Good to merge?

> I think, if we add a lot of languages, it may be good to move the Genericons/icon font styles above them, but that's minor and we can cross that bridge when we get to it.

Hopefully we won't have any icon font styles much longer ( #206 )

2016-10-10 21:33 UTC, laurelfulford commented
> Cool. Good to merge?

I took a closer look and I can see a couple minor formatting tweaks that will make this CSS match the rest of the file:

* On lines 553 and 563, a space should be added after `font-family:`.
* On the same lines, `Hiragino Kaku Gothic Pro` should be wrapped in double-quotes, rather than single quotes.

That's it!

> Hopefully we won't have any icon font styles much longer

Right! Good point. :)

2016-10-11 17:52 UTC, melchoyce requested changes

2016-10-11 17:52 UTC, melchoyce commented on style.css
> +	font-family:'Hiragino Kaku Gothic Pro', Meiryo, sans-serif;
Need a space between `font-family:` and `'Hiragino'`

2016-10-11 17:52 UTC, melchoyce commented on style.css
> +	font-family:'Hiragino Kaku Gothic Pro', Meiryo, sans-serif;
Need a space between font-family: and 'Hiragino'

2016-10-11 17:52 UTC, melchoyce commented on style.css
> +	font-family:'Hiragino Kaku Gothic Pro', Meiryo, sans-serif;
`Hiragino Kaku Gothic Pro` should be wrapped in `""`, not `''`

2016-10-11 17:52 UTC, melchoyce commented on style.css
> +	font-family:'Hiragino Kaku Gothic Pro', Meiryo, sans-serif;
`Hiragino Kaku Gothic Pro` should be wrapped in `""`, not `''`

2016-10-12 01:56 UTC, ntwb requested changes
Added a couple more coding standards issues

2016-10-12 01:56 UTC, ntwb commented on style.css
> +	font-weight: bold;
This should be numeric, i.e. `700`, not `bold`

2016-10-12 01:56 UTC, ntwb commented on style.css
> +html[lang="ja"] h1,
There's a trailing space at the end of this line that should be removed

2016-10-12 01:56 UTC, ntwb commented on style.css
> +html[lang="ja"] h2,
Another trailing space at the end of this line that should be removed

2016-10-13 01:19 UTC, melchoyce commented
Hi @nukaga, do you know if you'll have time to update this PR within the next couple of days? If not, please let us know and someone else can finish it. :) Thanks!

2016-10-14 18:48 UTC, melchoyce commented
Continuing this PR in #317.

2016-10-14 18:48 UTC, closed without merging