Custom colors first pass
WordPress/twentyseventeen pull request #167
Opened 2016-10-06 18:18 UTC by celloexpressions

See #116.

2016-10-10 02:20 UTC, ntwb requested changes
Added a couple of comments for spaces after commas

2016-10-10 02:20 UTC, ntwb commented on assets/css/colors-dark.css
> +	background: linear-gradient(to bottom,  rgba(255,255,255,0) 0%,rgba(255,255,255,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
Expected single space after commas on the above 3 lines

2016-10-10 02:20 UTC, ntwb commented on assets/css/colors-dark.css
> +		background: linear-gradient(to bottom,  rgba(255,255,255,0) 0%,rgba(255,255,255,0.3) 75%,rgba(255,255,255,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
Expected single space after commas on the above 3 lines

2016-10-10 17:49 UTC, celloexpressions commented on assets/css/colors-dark.css
> +	background: linear-gradient(to bottom,  rgba(255,255,255,0) 0%,rgba(255,255,255,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
This is a direct copy/paste from style.css, but swapping out the colors; it will need to be updated there as well.

2016-10-11 01:52 UTC, ntwb commented on assets/css/colors-dark.css
> +	background: linear-gradient(to bottom,  rgba(255,255,255,0) 0%,rgba(255,255,255,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
Yup, #169 gets all the coding standards sorted for style.css

2016-10-12 22:46 UTC, ryelle commented on inc/customizer.php
> +	if ( array_key_exists( $input, $valid ) ) {
This should be `in_array`, since `$valid` is not a keyed array. Right now this doesn't save `colorscheme`.

2016-10-13 05:56 UTC, celloexpressions commented
The one remaining Travis CI failure is for line endings, which I'm unable to change from here. Someone will need to fix that on or after merge.

This should be ready to go. After the initial merge, someone will need to go through and merge all changes to `style.css` after October 4th that impact colors in any way back to `color-patterns.php` and `colors-dark.css`. All future commits to `style.css` that touch colors need to consider the color files as well now too. This applies to any color, including white or black.

2016-10-14 22:16 UTC, merged