Adds validation fixes according to WordPress CSS coding standards [touch:12]
WordPress/twentyseventeen pull request #169
Opened 2016-10-06 18:44 UTC by marcustisater

I went through all the selectors properties to match the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/). One thing I noticed is that comments do not follow the best practices and sometimes it's unorganized, I will created an issue about this a bit more in-depth.

I would also like to point out that there are a lot of heavy selectors that will make it more difficult to override for developers when creating an child theme, also something we should consider refactoring. 

Happy to help, will try to get myself involved more into refactoring the CSS.

2016-10-06 23:55 UTC, ntwb requested changes
@marcustisater This is pretty close to perfect, I've added some notes for review.

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	outline: 1px dotted buttontext;
Although not a requirement the suggestion is to maintain CamelCase:
> via https://www.w3.org/TR/CSS22/ui.html#system-colors
> "Although these are case-insensitive, it is recommended that the mixed capitalization shown below be used, to make the names more legible."

WordPress core doesn't use any system colors currently so there's no "prior art" in this regard, I think we should use the more broadly used CamelCase here though.

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	font-weight: 900;
I think this should remain `bolder`

In a more broader scenario I think the WordPress CSS Coding Standards should allow the use of `bolder` and `lighter` relative weights

2016-10-06 23:55 UTC, ntwb commented on style.css
> +		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#4d000000', GradientType=0); /* IE6-9 */
Expected double quotes

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#4d000000', GradientType=0); /* IE6-9 */
Expected double quotes

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	background: -moz-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 100%); /* FF3.6-15 */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	background: -webkit-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 100%); /* Chrome10-25,Safari5.1-6 */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-06 23:55 UTC, ntwb commented on style.css
> +	background: linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-06 23:55 UTC, ntwb commented on style.css
> +		background: -moz-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 75%, rgba(0,0,0,0.3) 100%); /* FF3.6-15 */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-06 23:55 UTC, ntwb commented on style.css
> +		background: -webkit-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 75%, rgba(0,0,0,0.3) 100%); /* Chrome10-25,Safari5.1-6 */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-06 23:55 UTC, ntwb commented on style.css
> +		background: linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 75%, rgba(0,0,0,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
A single space should follow every comma `,`, i.e. `rgba(0, 0, 0, 0)` not `rgba(0,0,0,0)`

2016-10-07 00:09 UTC, ntwb commented on style.css
> +	  padding: 0.75em 1.25em;
This should be indented 1 tab, not 2 spaces

2016-10-07 05:01 UTC, akshayvinchurkar commented on style.css
> +	background: -moz-linear-gradient(top, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 100%); /* FF3.6-15 */
for better readability you are right.

2016-10-07 05:02 UTC, akshayvinchurkar commented on style.css
> +	  padding: 0.75em 1.25em;
keep the same indentation in all rules

2016-10-07 07:19 UTC, marcustisater commented
Thanks @ntwb, I will go through the notes. I wasn't really sure about the gradient stuff.

2016-10-07 08:07 UTC, ntwb commented
@marcustisater, yeah, I've got a follow up issue to create for the gradients, I'll do that as a separate issue though, as it's more a bug than a coding standard change.

2016-10-07 19:38 UTC, marcustisater commented
Thanks Stephen for the review, I completely agree with you. I went through your notes but the only thing I didn't quite understand was the double quotes part for the gradient, I am not used to writing them :joy:

2016-10-08 01:13 UTC, ntwb commented
@marcustisater change the single quote `'` to double quote `"` e.g:

From: `filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#4d000000', GradientType=0); /* IE6-9 */`

to: `filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#00000000", endColorstr="#4d000000", GradientType=0); /* IE6-9 */`

2016-10-08 01:16 UTC, ntwb commented
This https://github.com/WordPress/twentyseventeen/pull/169/commits/9218f4bf005de8cde56989ddbdf74345dadc3ecd commit should NOT be part of this PR.

2016-10-08 10:30 UTC, marcustisater commented
Sorry, bad habit.

All good now? It should remove 9218f4b from this PR now.

2016-10-08 21:51 UTC, ntwb requested changes
Added a couple of notes for two issue of space after comma

2016-10-08 21:51 UTC, ntwb commented on style.css
> +		background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0,0,0,0.3) 75%, rgba(0, 0, 0, 0.3) 100%); /* Chrome10-25,Safari5.1-6 */
Expected single space after `,` (The middle set of RGB values)

2016-10-08 21:51 UTC, ntwb commented on style.css
> +		background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(0,0,0,0.3) 75%, rgba(0, 0, 0, 0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
Expected single space after `,` (Same middle set of RGB values)

2016-10-09 06:03 UTC, marcustisater commented
Thanks, that must have slipped by... :blush:

2016-10-09 06:53 UTC, ntwb approved these changes
Looks good 👍🏻

2016-10-09 07:03 UTC, marcustisater commented
@davidakennedy look through and merge, then we can get on to #194. Thanks for the review once again @ntwb

2016-10-15 15:11 UTC, marcustisater commented
@melchoyce I resolved the conflicts, can be merged.

2016-10-16 06:15 UTC, davidakennedy commented
@marcustisater Thanks for the work here – sorry this didn't get merged sooner. Closing this out as I think most of this has been taken care of in other PRs. Thanks for the reviews @ntwb!

2016-10-16 06:15 UTC, closed without merging

2016-10-16 06:44 UTC, ntwb commented
The fast pace changes reflected in `style.css` made this PR tricky to say the least, wait for a review, make changes, rebase, make more changes, wait for another review, rebase, rinse and repeat 😖 

That said I'm still seeing 100+ CSS coding standards issues, there is probably 2 ways to go away fixing these:

1. Small pull requests updating only a small set of changes, e.g A PR switching from named font weight values to numeric, then another PR removing trailing zeros from values etc, that should allow for quicker code review and hopefully not need rebasing before merge etc.

2. I can submit a PR making all the changes in one swoop at a time organised in Slack where it can be discussed and merged before other PRs cause merge conflicts etc

I'll also echo @davidakennedy comment @marcustisater, top work here and thanks 👍

2016-10-17 08:59 UTC, marcustisater commented
ok no worries.