Delete the rule for align content with top navbar on small screens
WordPress/twentyseventeen pull request #182
Opened 2016-10-07 06:29 UTC by akshayvinchurkar

Delete the rule for align content with top navbar on small screens

2016-10-11 00:39 UTC, melchoyce commented
Is this PR replacing #181?

2016-10-11 01:49 UTC, ntwb requested changes

2016-10-11 01:49 UTC, ntwb commented on style.css
> +}
Don't delete the newline at the end of the file

2016-10-12 05:33 UTC, akshayvinchurkar commented
ya first i just comment that code but reviewer says you have to delete the code so i delete that its replacing my first PR

2016-10-12 14:43 UTC, melchoyce commented
Thanks, I've gone ahead and deleted the old one.

2016-10-18 00:53 UTC, davidakennedy commented
Hey @akshayvinchurkar! Thanks for the pull request. I'm not exactly sure what this fixes, and it looks like this change would effect a lot of the styles in a negative way.

I'm going to close this, but please feel free to create a new issue if the problem persist. A screenshot showing the problem would be helpful.

2016-10-18 00:53 UTC, closed without merging