update some hover styles for better look
WordPress/twentyseventeen pull request #183
Opened 2016-10-07 06:55 UTC by akshayvinchurkar

2016-10-10 02:26 UTC, ntwb requested changes
Add some coding standards issues to be fixed.

2016-10-10 02:26 UTC, ntwb commented on style.css
> +.comment-reply-link:hover{
Expected a single space before the open `{` brace

i.e. `.comment-reply-link:hover {`, not `.comment-reply-link:hover{`

2016-10-10 02:26 UTC, ntwb commented on style.css
> +	padding: 2px 5px 2px 5px;
Use shorthand `padding: 2px 5px;` rather than `padding: 2px 5px 2px 5px;`

2016-10-10 04:49 UTC, akshayvinchurkar reviewed
Please re-review the changes and merge the request

2016-10-11 00:40 UTC, melchoyce commented
Can you provide before and after screenshots of what you're changing in this PR?

2016-10-11 01:49 UTC, ntwb requested changes

2016-10-11 01:49 UTC, ntwb commented on style.css
> +}
Don't delete the newline at the end of the file.

2016-10-11 04:14 UTC, josephfusco commented on style.css
> +	padding: 2px 5px 2px 5px;
We shouldn't be changing padding on hover as it affects layout and does not offer a high performance transition.

See: [https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/#toc-animating-layout-properties](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/#toc-animating-layout-properties)

2016-10-11 04:17 UTC, josephfusco commented
@melchoyce https://cloudup.com/cYlHVZQec08

2016-10-11 14:15 UTC, melchoyce commented
Thanks for the video, @josephfusco. @akshayvinchurkar, thanks for your contribution. Looking at the change, I don't think this is a good fit for Twenty Seventeen. I'm going to close this PR, but thanks for your thoughts and for experimenting.

2016-10-11 14:15 UTC, closed without merging

2016-10-12 05:29 UTC, akshayvinchurkar commented
on hover it looks like he cant breeth in that small area 😅

2016-10-12 18:24 UTC, melchoyce commented
We're look at overall link hovers in #222. Please keep an eye out there :)