Post date, title, and content vertically misaligned #162
WordPress/twentyseventeen pull request #186
Opened 2016-10-07 08:04 UTC by akshayvinchurkar

This issue is small but i fixed it with this small tweak

2016-10-12 03:08 UTC, laurelfulford commented on style.css
> +	margin-left:-2px;
Minor formatting change - please add a space after the colon.

2016-10-12 03:09 UTC, laurelfulford commented on style.css
> +}
Please don't remove the line break at the end of the file - thanks!

2016-10-12 03:11 UTC, laurelfulford commented
Thanks for this PR, @akshayvinchurkar!

I added a couple notes for changes in the code. Could you also update the rtl.css styles to match, so they remove this negative left margin and add a negative right margin instead?

Let me know if you have any questions at all about this - thanks!

2016-10-12 06:09 UTC, akshayvinchurkar commented on style.css
> +	margin-left:-2px;
i fix this

2016-10-12 08:16 UTC, ntwb requested changes
A couple of issues of whitespace added where it should not be

2016-10-12 08:16 UTC, ntwb commented on style.css
> +
Remove this tabbed whitespace

2016-10-12 08:16 UTC, ntwb commented on style.css
> +	}
Also remove this tabbed whitespace

2016-10-13 05:27 UTC, ntwb requested changes
Lines 3333 & 3334 are indented with spaces, they should be indented with tabs please

2016-10-13 05:27 UTC, ntwb commented on style.css
Tabs not spaces please

2016-10-13 05:27 UTC, ntwb commented on style.css
> +	        margin-left: -20%;
Tabs not spaces please

2016-10-15 04:04 UTC, davidakennedy commented
Adjusted and merged in #333.

2016-10-15 04:04 UTC, closed without merging