Fixed: Admin Bar overlap issue with main menu.
WordPress/twentyseventeen pull request #187
Opened 2016-10-07 08:59 UTC by Swapnildhanrale

The default WordPress admin bar height is 46px, and we give top 32px to the menubar we need to give this 46px, means when the menu is fixed then it will get top 46px and not overlap with the admin bar.

2016-10-08 07:43 UTC, Swapnildhanrale commented
Now, The used `px` unit to fix this issue. We'll be able to use unit `em` like this.

```
@media screen and (max-width: 48.8em) and (min-width: 48em) {
    .admin-bar .site-navigation-fixed.navigation-top,
    .admin-bar .site-navigation-hidden.navigation-top {
        top: 46px;
}
```

2016-10-12 20:17 UTC, melchoyce commented
Looks like this PR has some conflicts with style.css now.

2016-10-12 23:37 UTC, ntwb requested changes

2016-10-12 23:37 UTC, ntwb commented on style.css
> +
Remove this blank line please

2016-10-13 12:44 UTC, ntwb approved these changes

2016-10-13 12:46 UTC, Swapnildhanrale commented on style.css
> +
Removed the wanted space from this line

2016-10-13 12:47 UTC, Swapnildhanrale commented
Merged `master` branch in `admin-bar-overlap-issue`. Ready for merge.

2016-10-14 15:39 UTC, Swapnildhanrale commented
Merged WordPress:master branch in Swapnildhanrale:admin-bar-overlap-issue. Ready for merge.

2016-10-14 17:06 UTC, laurelfulford commented on style.css
> +}
Can you please add a new line to the end of the file?

2016-10-14 17:07 UTC, laurelfulford commented
@Swapnildhanrale the fix looks good! Can I just get you to add a new line to the very end of the style.css for correct formatting? Thanks!

2016-10-15 03:22 UTC, merged

2016-10-15 03:29 UTC, davidakennedy commented
@Swapnildhanrale Thanks for your contribution! What's your GitHub user name, so I can ensure you receive props in WordPress 4.7?

2016-10-17 06:47 UTC, Swapnildhanrale commented
Hi @davidakennedy my username is **swapnilld**

2016-12-07 13:55 UTC, Swapnildhanrale commented
Hi @davidakennedy I am extremely sorry. I have given the wrong username, my username is  [https://profiles.wordpress.org/swapnild](https://profiles.wordpress.org/swapnild). It is my first time in the contribution of WordPress can you please update my name in core contributors list.

2016-12-08 16:58 UTC, davidakennedy commented
Hi @Swapnildhanrale! I'm really sorry about that! Typos are easy to make, especially if you're excited about your first contribution. 😄 

It looks like you can be added to the credits page retroactively. See: https://wordpress.slack.com/archives/core-committers/p1481216033000020

So we'll fix it soon! Thank you for your contribution!

2016-12-08 17:00 UTC, davidakennedy commented
Fixed here: https://meta.trac.wordpress.org/changeset/4507

cc: @Swapnildhanrale

2016-12-08 17:02 UTC, ocean90 commented
FYI: Credits are cached in several places so it can take up to 24 hours until it's visible in all lists.