Galleries
WordPress/twentyseventeen pull request #201
Opened 2016-10-07 22:25 UTC by jordesign

I've updated the basic styles for default WordPress Galleries. A lot of it was just undoing some wayward styles that were being applied. 

**Before**
![screen shot 2016-10-08 at 12 39 53 am](https://cloud.githubusercontent.com/assets/1842363/19206998/ad1e91f4-8d38-11e6-8ddf-2f4d300052f0.jpg)

**After**
![screen shot 2016-10-08 at 9 10 59 am](https://cloud.githubusercontent.com/assets/1842363/19207002/b933c22a-8d38-11e6-995c-c726a270a4a5.jpg)

I've also collapsed the columns as screen size gets smaller (as anything more than 2col was very squishy

** Tablet-ish **
![screen shot 2016-10-08 at 9 11 19 am](https://cloud.githubusercontent.com/assets/1842363/19207023/dfea221a-8d38-11e6-956b-8bb94351aa4a.jpg)

** Mobile **
![screen shot 2016-10-08 at 9 11 34 am](https://cloud.githubusercontent.com/assets/1842363/19207028/ea67d5ac-8d38-11e6-88e6-e4f573360cf3.jpg)

**Captions **
Gallery Caption styles are being declared in the same rule as normal .wp-caption(s)

** Hover Styles **
Simple Hover styles on the image itself
![screen shot 2016-10-08 at 9 19 17 am](https://cloud.githubusercontent.com/assets/1842363/19207050/1329e19c-8d39-11e6-968f-6012dcb6566c.jpg)

2016-10-07 23:20 UTC, joyously commented
You left the 40px margins on `figure`?

2016-10-08 01:29 UTC, jordesign commented
@joyously Yeah - I wasn't sure if `figure` was going to be used in other contexts - so didn't want to change the global style

2016-10-08 02:41 UTC, grappler commented
It looking nicer, have you tested the different column sizes like 4 columns?

2016-10-08 03:54 UTC, jordesign commented
Working nicely with 4 columns - although it does start to get a bit squeezy in the available space. Anything of 5 columns or more means ridiculously small columns - but that's always going to be the case.

![image](https://cloud.githubusercontent.com/assets/1842363/19210198/1b1f2bea-8d67-11e6-8eb1-6ee0533d08e0.png)

2016-10-08 13:58 UTC, joyously commented
Your screen shot looks like it is a page because there is no sidebar. On mine, which is a post, it shows the images the size for 4 column, but only two fit across (that's without your mods).

2016-10-08 16:30 UTC, melchoyce commented
Looking really good. Can you get rid of the left margin on the left-most column and the right margin on the right-most column so it's full-width?

2016-10-08 17:33 UTC, josephfusco commented on style.css
>  }
Add new line after closing `}`

2016-10-08 17:34 UTC, josephfusco commented on style.css
Too many new lines between these. There should only be one.

2016-10-08 17:34 UTC, josephfusco commented on style.css
> +
Remove extra newline here.

2016-10-08 20:33 UTC, jordesign commented
@melchoyce The LHS and RHS padding is tricky as by default the thumbnails are set to be center aligned. This gives the neatest experience across a range of possible uses - particularly where the thumbnails may be of different widths. 

There are 2 approaches we _could_ take, although I don't love either of them:

- scale the images so they are always 100% of the `.gallery-columns-3 .gallery-item ` width - but this would mean scaling up the thumbnail/small images (when they are selected) which isn't ideal.

- have the thumbnails left aligned - which would keep things flush-left but have a larger gap on the right hand side. Also could result in some weird alignments when there are images of variable widths.

2016-10-08 20:36 UTC, jordesign commented
Thanks @josephfusco - definitely needs a tidy.

2016-10-08 21:28 UTC, ntwb requested changes
I've added some more coding standards notes

2016-10-08 21:28 UTC, ntwb commented on style.css
> +.wp-caption, .gallery-caption {
New lines for each selector, so this would be:
```css
.wp-caption, 
.gallery-caption {
```

2016-10-08 21:28 UTC, ntwb commented on style.css
> +	padding: 0 .5em;
Use a leading zero for decimal values, so `.5em` becomes `0.5em`

2016-10-08 21:28 UTC, ntwb commented on style.css
>  }
Properties should be followed by a colon and a space e.g. `background: none`, not `background:none`

2016-10-08 21:28 UTC, ntwb commented on style.css
> +	border:10px solid #ddd;
Properties should be followed by a colon and a space

2016-10-08 21:28 UTC, ntwb commented on style.css
> +	display:block;
Properties should be followed by a colon and a space

2016-10-08 22:02 UTC, ntwb commented on style.css
> +	margin: 0 0 1.5em 0;
Use shorthand properties, i.e.`margin: 0 0 1.5em;`, not `margin: 0 0 1.5em 0;`

2016-10-09 08:55 UTC, jordesign commented
Thanks @ntwb - I'll tidy those up.

2016-10-09 23:38 UTC, melchoyce commented
@jordesign I was thinking we'd increase spacing between the images to compensate for the lack of left/right margin — but maybe that would look ridiculous. Maybe we should just left-align.

2016-10-10 00:09 UTC, jordesign commented
@melchoyce Part of the problem is that gap is going to vary depending on screen size - so we can't really do it in a bulletproof way.

A quick visual preview of what left aligned would look like.
![image](https://cloud.githubusercontent.com/assets/1842363/19224844/d54eb896-8ed9-11e6-868d-fd1ad838f76b.png)

and preview with the hover style (which now appears outside the left margin)
![image](https://cloud.githubusercontent.com/assets/1842363/19224848/ee22dc9e-8ed9-11e6-971f-394111a106d0.png)

2016-10-10 00:33 UTC, melchoyce commented
Left aligned looks good 👍

2016-10-10 02:20 UTC, jordesign commented
Thumbnails are left aligned now. Works well at larger screens.
It's a little unbalanced on smaller screens (screenshot below) but I think it is a reasonable compromise.

![image](https://cloud.githubusercontent.com/assets/1842363/19225669/4240d634-8eec-11e6-8569-0ae9a2bd84a3.png)

2016-10-10 02:33 UTC, ntwb requested changes
Added a couple of coding standards issues

2016-10-10 02:33 UTC, ntwb commented on style.css
> +	background:none;
Expected a single space after the colon

2016-10-10 02:33 UTC, ntwb commented on style.css
> +	width:50%;
Expected a single space after the colon

2016-10-10 02:33 UTC, ntwb commented on style.css
> +	width:50%;
Expected a single space after the colon

2016-10-10 02:38 UTC, jordesign commented
Ah sorry about that - missed those ones. Update coming.

2016-10-10 20:18 UTC, melchoyce commented
Definitely coming along. I'm a little unsure about the super solid border on hover. All of the other borders are either 1px or 2px, so 10px feels out of place. I could see going up to 4px, but not really beyond that.

Alternately, we could do some sort of overlay on hover, or something similar. (Would be extra great to use CSS filters, since they're GPU accelerated, and figure out an IE and Opera-specific fallback.) What do you think about that, @jordesign?

2016-10-10 22:45 UTC, jordesign commented
@melchoyce good point - it does make the thick border out of place. I'll have a think about CSS filters - did you have anything in mind?

2016-10-10 23:38 UTC, melchoyce commented
@jordesign Thinking either opacity or brightness.

2016-10-10 23:40 UTC, jordesign commented
@melchoyce cool - I was thinking opacity too - maybe a little blur or greyscale with it too

2016-10-10 23:42 UTC, melchoyce commented
Unfortunately I think blur (and drop-shadow) _isn't_ GPU accelerated :/

2016-10-10 23:43 UTC, jordesign commented
ah ok - can just stick with opacity then. Is filter: opacity; better than just using opacity?

2016-10-10 23:49 UTC, melchoyce commented
Yup. IDK why. Browsers are weird.

2016-10-10 23:50 UTC, melchoyce commented
(More information on that from this awesome presentation by Will Boyd: https://youtu.be/bEoLCZzWZX8)

2016-10-11 00:21 UTC, josephfusco commented
>Unfortunately I think blur (and drop-shadow) isn't GPU accelerated :/

While those properties themselves aren't, if they are on/attached to a layer that is, the animation can still be silky smooth, but it really depends on how the moving parts are coded up. For example in the case of animating a box shadow on hover, you can have a layer behind an element that has a box shadow initially, and manipulate it with opacity. Would give the illusion of the box-shadow being animated without all the painting. :)

But +1 for just a simple opacity transition.

2016-10-11 00:33 UTC, melchoyce commented
That is very cool. Thanks for the info @josephfusco.

2016-10-11 00:52 UTC, melchoyce commented
Whatever's decided here for hovers should also get applied to regular linked images on hover. They look like this right now:

<img width="1240" alt="screen shot 2016-10-10 at 8 50 07 pm" src="https://cloud.githubusercontent.com/assets/2846578/19255396/72cae58a-8f2b-11e6-9a75-a4965b750f55.png">

2016-10-11 01:06 UTC, jordesign commented
@melchoyce agreed - will pop that in a separate PR once we've confirmed the style?

2016-10-11 01:13 UTC, melchoyce commented
@jordesign Sounds good!

2016-10-11 01:54 UTC, jordesign commented
A side note on left aligning images.... When we have a caption - the caption fills the available space to the next column

![image](https://cloud.githubusercontent.com/assets/1842363/19256138/da4b1c00-8faf-11e6-8e18-d8397648f7da.png)

2016-10-11 01:55 UTC, jordesign commented
Proposed style for hover images. :link on left, :hover on right
![image](https://cloud.githubusercontent.com/assets/1842363/19256354/f4fca8fa-8fb1-11e6-895e-98d447bf7279.png)

- 

-

2016-10-11 02:22 UTC, melchoyce commented
> A side note on left aligning images.... When we have a caption - the caption fills the available space to the next column

Bummer... just an unavoidable issue with default WordPress galleries?

> Proposed style for hover images. :link on left, :hover on right

Looks good from what I can tell.

2016-10-11 02:30 UTC, jordesign commented
re: caption The tricky thing is that the width of the caption takes the full column - regardless of the size of the image. When everything is centered - it is less noticeable as it still feeld balanced.

2016-10-11 03:45 UTC, ntwb requested changes
Coding standards fixes

2016-10-11 03:45 UTC, ntwb commented on style.css
> +	margin: 0 0 1.5em 0;
Use shorthand `margin: 0 0 1.5em;`

2016-10-11 03:45 UTC, ntwb commented on style.css
> +	transition: filter .2s ease-in;
Decimals need a leading zero, `0.2s`, not `.2s`

2016-10-11 03:45 UTC, ntwb commented on style.css
> +	/* Gallery Columns */
Is this change a switch from a tab to a space? i.e. I hope it's not the other way around from a space to a tab.

2016-10-11 03:45 UTC, ntwb commented on style.css
> +0
Keep the newline but remove the `0`

2016-10-11 04:27 UTC, jordesign commented
Coding standards fixes in place, and merged to current master

2016-10-11 04:50 UTC, joyously commented
> Proposed style for hover images. :link on left, :hover on right
I think that looks awful (as on the other non-gallery images). Couldn't you use a minor scale change instead of opacity?

2016-10-11 04:54 UTC, jordesign commented
Hey @joyously - can you elaborate on what makes it awful?
In the context of the change animating on hover - it makes a lot more sense than just a static image.

2016-10-11 05:14 UTC, joyously commented
I think changing opacity is awful because it degrades the image. It looks bad, so it is using animation for no good reason. If you use something like scale(1.1), it looks like it zooms in a little on hover instead of occluding the image. And remember, touch devices don't have hover, so it's a subset of users seeing it.

2016-10-11 05:25 UTC, jordesign commented
The scaling effect _is_ quite a nice one... :)
@melchoyce do you have a thought on this?

2016-10-11 17:33 UTC, melchoyce commented
Reviewing the updates — something about it feels kind of laggy and slow? Playing with it in practice, I'm not sure about the greyscale. What do you think about this instead?

```.gallery-item a:hover img {
	filter: opacity(60%);
}```

Not a huge fan of scaling overall, after using it in prior themes.

2016-10-11 22:37 UTC, jordesign commented
I'm totally happy with that aesthetically - and happy for it to be your call too. PR is updated.

2016-10-12 20:11 UTC, laurelfulford commented on style.css
> +
There's an extra space here - the `}` should just be on the line immediately following `background: none;`.

2016-10-12 20:13 UTC, laurelfulford commented on style.css
> +
Small nitpick: this space can probably go, too - all other `@media` queries finish with the last two `}` on different lines, but without an extra line break between them.

2016-10-12 20:22 UTC, laurelfulford commented on style.css
>  	width: 100%;
Looks like the width is declared twice here - can the unneeded one be removed?

2016-10-12 20:28 UTC, laurelfulford commented
@jordesign, these are looking really good - thanks for this! 

I found a couple other small nitpicks in the code that I added as notes. 

I also spotted a couple minor things while reviewing - when I use the One column layout, it displays as four columns:

![Image](https://cldup.com/aPwrYXHQ7A-3000x3000.png)

The rtl.css styles should also be updated, just for the `.gallery-item` text alignment. 

That should be it! Thanks again for getting these looking sharp, and if you have any questions about the above just let me know!

2016-10-12 21:01 UTC, jordesign commented
Thanks @laurelfulford - I'll get those change happening today

2016-10-12 21:39 UTC, jordesign commented
Just pushed up a bunch of updates for:
- Whitespace removal
- Making sure 1 & 2 column grids work
- rtl styles

2016-10-12 22:02 UTC, joyously commented
Did those updates include the original fix for the columns? My 4 column gallery is still only showing 2 columns.

2016-10-12 22:35 UTC, jordesign commented
Should all be good for 4 columns (working for me locally) unless I've missed a particular use-case

2016-10-12 23:36 UTC, ntwb requested changes
Added some coding standards issues and a question on a vendor prefix addition

2016-10-12 23:36 UTC, ntwb commented on rtl.css
> +	text-align:right;
A space is required after the colon please

2016-10-12 23:36 UTC, ntwb commented on rtl.css
> +
Only a single blank line here, not 3 blank lines

2016-10-12 23:36 UTC, ntwb commented on style.css
> +	width:100%;
A space after the colon

2016-10-12 23:36 UTC, ntwb commented on style.css
> +	-webkit-backface-visibility: hidden;
Why the webkit vendor prefix `-webkit-backface-visibility` property if you're not using `backface-visibility`?

2016-10-12 23:37 UTC, joyously commented
After you pushed those updates, I downloaded the master zip and overwrote my local install. My 4 column and 3 column galleries still only have 2 columns.

2016-10-12 23:52 UTC, jordesign commented on style.css
> +	-webkit-backface-visibility: hidden;
missed this one - sorry

2016-10-12 23:55 UTC, jordesign commented
@joyously Could you check in the chrome inspector or something and let me know what styles are being applied to the .gallery-item div? Screenshot of the applied styles would be great - help me troubleshoot

2016-10-13 00:12 UTC, joyously commented
I was misunderstanding where your changes were committed. I thought you had merged those last ones into master. I downloaded the zip of this branch and I do see your changes, but the thumbnails for my 4 column gallery are the same size as the 3 column gallery. And they overlap a **lot**. They also overlap the sidebar a little bit.  What happened to the rules for sizing the thumbnails?
![overlapping-gallery](https://cloud.githubusercontent.com/assets/7957680/19332195/72548176-90af-11e6-94c7-d238f6e2d4c2.jpg)

2016-10-13 00:17 UTC, jordesign commented
@joyously there's a universal rule in the stylesheet setting a max width on images
![image](https://cloud.githubusercontent.com/assets/1842363/19332306/8009bc3c-9136-11e6-87ec-d299f0882b55.png)

not sure why that's not coming through for you - but there's definitely some strange things going on for you there compared to what it should be doing.

2016-10-13 00:17 UTC, jordesign commented on rtl.css
> +	text-align:right;
fixed

2016-10-13 00:17 UTC, jordesign commented on rtl.css
> +
fixed

2016-10-13 00:17 UTC, jordesign commented on style.css
> +	width:100%;
fixed

2016-10-13 00:28 UTC, melchoyce commented
Testing through git, looks like everything's working as expected. 

The combination of the margin-bottom on the `figure` and on `.gallery` means there's a lot of extra space at the bottom:

<img width="607" alt="screen shot 2016-10-12 at 8 27 27 pm" src="https://cloud.githubusercontent.com/assets/2846578/19332482/682c9142-90ba-11e6-9537-9b3ea5fb8493.png">

Anything we can do to tighten that up?

2016-10-13 00:30 UTC, ntwb approved these changes

2016-10-13 00:37 UTC, joyously commented
@jordesign yes, I have the rule for max-width:100%. That's not the problem. The problem is I don't see any rules for 4 column (25%) and 3 column(33%), so my thumbnails are not getting sized down.

2016-10-13 00:51 UTC, jordesign commented
@melchoyce Tightened up the bottom margins so there's no double up on the bottom margin. Also tidied up the margin at the bottom of captions too

2016-10-13 00:57 UTC, melchoyce commented
Looks good to me!

2016-10-13 05:49 UTC, jordesign commented
Cool - should be good from my end too then.

2016-10-14 04:29 UTC, ryelle commented on style.css
> +.wp-caption,
Remove the trailing space here

2016-10-14 04:29 UTC, ryelle commented on style.css
> +
Remove this extra line & tab

2016-10-14 04:29 UTC, ryelle commented on style.css
> +.gallery-columns-2 .gallery-item {
I think this ruleset should live up near `.gallery-columns-1 .gallery-item` (or that one should be down here, either way they should be together)

2016-10-14 04:29 UTC, ryelle commented on style.css
> +	.gallery-columns-4 .gallery-item {
This is redundant, since `.gallery-item` is already `max-width: 25%`, but might be good to leave for clarity? I'm not sure.

2016-10-14 04:29 UTC, ryelle commented on style.css
> +
Remove the stray tab here

2016-10-14 04:29 UTC, ryelle commented on style.css
> +
Remove the stray tab here

2016-10-14 05:49 UTC, jordesign commented on style.css
> +.gallery-columns-2 .gallery-item {
Good call

2016-10-14 05:52 UTC, jordesign commented on style.css
> +	.gallery-columns-4 .gallery-item {
I like the idea of it being there for clarity/completeness if that is allowed?

2016-10-14 05:56 UTC, jordesign commented on style.css
> +.wp-caption,
removed

2016-10-14 05:56 UTC, jordesign commented on style.css
> +
removed

2016-10-14 05:57 UTC, jordesign commented on style.css
> +
removed

2016-10-14 05:57 UTC, jordesign commented on style.css
> +.gallery-columns-2 .gallery-item {
moved

2016-10-14 05:57 UTC, jordesign commented on style.css
> +
removed

2016-10-14 14:19 UTC, ryelle commented on style.css
> +	filter: opacity(60%);
One more trailing space to remove

2016-10-14 14:24 UTC, ryelle commented on style.css
> +	.gallery-columns-4 .gallery-item {
Sounds good, if anyone thinks different we can address it later. 👍

2016-10-14 15:19 UTC, joyously commented
@jordesign  I found the problem. There is a rule for `.gallery-item a {display: inline-block;}` that makes the image ignore the max-width on the `figure`. You might not see this problem because probably your test setup is using the default media sizes. I think those are small, so I have my thumbnails set at 200.
I have a 4 column gallery followed by a 3 column gallery.
Here is what I see with your latest changes: a lot of overlap
![inline-block-galleries](https://cloud.githubusercontent.com/assets/7957680/19392696/84eb0a28-91f7-11e6-8e23-bb129dae70e5.jpg)

And with one minor change, I get this: proper thumbnail sizing
![inline-galleries](https://cloud.githubusercontent.com/assets/7957680/19392718/9b6e2b72-91f7-11e6-8d70-b62a0dec848e.jpg)

2016-10-15 04:36 UTC, jordesign commented
@ryelle trailing space removed - sorry about that.
@joyously - that's so bizarre - I don't get that behaviour at all. But I didn't get any drapbacks from removing that rule either - so it is gone - so hopefully the problem is fixed.

2016-10-15 20:32 UTC, merged

2016-10-15 20:34 UTC, davidakennedy commented
Thanks @jordesign! Epic work here. I made a few tweaks to fix up some things in https://github.com/WordPress/twentyseventeen/pull/362/commits/300788d336912d416a926c8b5d5b323c772f506d.