Add a background and border-bottom to featured images.
WordPress/twentyseventeen pull request #228
Opened 2016-10-09 22:48 UTC by melchoyce

Fixes #15.

2016-10-09 23:43 UTC, grappler requested changes

2016-10-09 23:43 UTC, grappler commented on style.css
> +    background-color: #fafafa;
This should be a tab and not spaces

2016-10-09 23:47 UTC, melchoyce commented on style.css
> +    background-color: #fafafa;
The rest of the stylesheet seems to be spaces, though?

2016-10-09 23:57 UTC, grappler commented on style.css
> +    background-color: #fafafa;
I see something different

![image](https://cloud.githubusercontent.com/assets/1785641/19224770/8783dd4c-8ec7-11e6-9dc3-d553c62b77a6.png)

2016-10-10 00:16 UTC, melchoyce commented on style.css
> +    background-color: #fafafa;
Weird... I'll copy/paste from existing indents and see if that fixes it.

2016-10-10 00:35 UTC, grappler approved these changes

2016-10-10 00:36 UTC, merged

2016-10-10 00:36 UTC, melchoyce commented
Thanks @grappler.