No footer list underline
WordPress/twentyseventeen pull request #234
Opened 2016-10-10 03:21 UTC by jordesign

re #158 

This removes the underline on links within li elements in the footer widgets.
It also offers an alternative style of abbr so as not to clash with the horizontal rules throughout the site.

![image](https://cloud.githubusercontent.com/assets/1842363/19226263/b045f756-8ef4-11e6-9a7a-b1bf7c76b58d.png)

user: @jordesign

2016-10-10 19:57 UTC, melchoyce commented
Hey @jordesign, would you mind splitting these out into two PRs? One for removing the footer list link underlines, and one for the alternate `abbr` styling?

2016-10-11 02:16 UTC, jordesign commented
This PR is now just the underline on footer widgets - with new abbr styling removed

2016-10-11 02:19 UTC, ntwb requested changes

2016-10-11 02:19 UTC, ntwb commented on style.css
> + {
The opening brace should be on the previous line with a single space preceeding it.

2016-10-11 02:25 UTC, melchoyce commented
Looks good 👍

2016-10-11 02:25 UTC, merged