Remove double border footer
WordPress/twentyseventeen pull request #235
Opened 2016-10-10 03:36 UTC by jordesign

re: #196 styles to use margin instead of padding on borders on .entry-footer and .site-footer so the border's don't combine to form a 2px section

2016-10-10 03:49 UTC, ntwb requested changes

2016-10-10 03:49 UTC, ntwb commented on style.css
> +	margin: 2em 0 0 0;
Use shorthand `margin: 2em 0 0;`, not `margin: 2em 0 0 0;`

2016-10-11 04:52 UTC, jordesign commented
This PR has become a bit muddied once merged with current master. It seems possibly less needed?

At any rate - it now separates .entry-footer and .site-footer as referenced in #196 
![image](https://cloud.githubusercontent.com/assets/1842363/19259158/c3c96f52-8fca-11e6-8808-fd574107c4d6.png)

2016-10-11 09:45 UTC, ntwb requested changes

2016-10-11 09:45 UTC, ntwb commented on style.css
> +		margin-top:3em;
Expected a single space after the colon

2016-10-13 01:56 UTC, melchoyce commented
Except for when comments exist on pages, I don't think we actually need the bottom border. I'd rather have the top border on the footer be the divider instead:

<img width="1135" alt="screen shot 2016-10-12 at 9 55 41 pm" src="https://cloud.githubusercontent.com/assets/2846578/19333960/aa1442ec-90c6-11e6-89a1-3a0b52cc565d.png">

2016-10-13 04:23 UTC, jordesign commented
I reckon even on a page _with_ comments it isn't needed.

Before:
![image](https://cloud.githubusercontent.com/assets/1842363/19336606/9a679bf4-9158-11e6-85e5-87e1614fd7f8.png)

After:
![image](https://cloud.githubusercontent.com/assets/1842363/19336655/e20119fe-9158-11e6-940f-b2da9121869b.png)

Only strange outlier seems to be if comments are on and we have post-paging. But I think it still looks alright.
![image](https://cloud.githubusercontent.com/assets/1842363/19336671/02772e62-9159-11e6-8279-5551df7f9e46.png)

2016-10-13 04:24 UTC, jordesign commented on style.css
> +		margin-top:3em;
this is fixed now

2016-10-15 06:59 UTC, laurelfulford commented on style.css
> -	-webkit-backface-visibility: hidden;
This was added to fix #212 - is there a reason it's being removed here?

2016-10-15 07:01 UTC, laurelfulford commented
This fix looks good @jordesign! Added a question about an unrelated code change, but once that's figured out this should be good to go :)

2016-10-15 09:02 UTC, jordesign commented
There was no good reason for that backface visibility being removed - i may have been in the wrong branch. I've popped it back in.

2016-10-15 19:35 UTC, merged