Swap tagline color for opacity
WordPress/twentyseventeen pull request #243
Opened 2016-10-11 02:07 UTC by melchoyce

Swapping tagline color from #bbb to white (the site title color), and
using opacity to make it lighter.

2016-10-11 02:11 UTC, ntwb requested changes

2016-10-11 02:11 UTC, ntwb commented on style.css
> +    opacity: 0.8;
Tabs, not spaces

2016-10-11 02:14 UTC, melchoyce commented on style.css
> +    opacity: 0.8;
Sorry, I keep pasting in from Inspector. Will fix (along with the merge conflicts)

2016-10-12 20:59 UTC, josephfusco approved these changes

2016-10-12 21:10 UTC, merged