Remove indentation on figure elements.
WordPress/twentyseventeen pull request #257
Opened 2016-10-11 23:23 UTC by mor10

Resolves alignment issues on captioned images. Fixes #256

2016-10-12 03:27 UTC, ntwb requested changes

2016-10-12 03:27 UTC, ntwb commented on style.css
> +}
Don't remove the blank newline at the end of the file

2016-10-12 21:01 UTC, josephfusco commented
Waiting for more feedback on #256

2016-10-12 23:17 UTC, ntwb approved these changes

2016-10-13 18:27 UTC, josephfusco approved these changes

2016-10-13 18:48 UTC, josephfusco commented
Looks good thank you @mor10 ! 👍

2016-10-14 14:54 UTC, merged