"Scroll down" arrow in homepage menu is misaligned #273
WordPress/twentyseventeen pull request #278
Opened 2016-10-13 05:31 UTC by akshayvinchurkar

This will fixed the arrow placement

2016-10-13 05:37 UTC, ntwb requested changes

2016-10-13 05:37 UTC, ntwb commented on style.css
> +}
Please, don't remove the newline from the end of the file

2016-10-13 05:43 UTC, akshayvinchurkar commented on style.css
> +}
i did not even touch the code i just make 0.76em to 0.40em and thats it😒 how this is possible😕

2016-10-13 15:23 UTC, melchoyce commented on style.css
> +}
Maybe it's something your code editor does automatically?

2016-10-15 05:15 UTC, merged

2016-10-15 05:16 UTC, davidakennedy commented
Fixed here: https://github.com/WordPress/twentyseventeen/commit/71430139d7bb1046a30b628b4f2094461274e1ef