Fixes/issue 281 editor styles
WordPress/twentyseventeen pull request #318
Opened 2016-10-14 19:40 UTC by laurelfulford

Doing a first pass of editor-styles.css. See #281.

2016-10-15 20:33 UTC, josephfusco commented
Looks good to me!

2016-10-15 20:35 UTC, josephfusco commented
We will need to remind any existing PRs to also update any applicable styles in editor-style.css.

2016-10-15 23:04 UTC, ntwb requested changes
@laurelfulford Added CSS coding standards notes

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +	font-weight: normal;
Numeric font values, `400`, not `normal`

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +	font-weight: bold;
Numeric font values, `700`, not `bold`

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> + .gallery {
Remove the space before the period at the start of the line

2016-10-15 23:04 UTC, ntwb commented on functions.php
>  add_action( 'after_setup_theme', 'twentyseventeen_setup' );
Add a blank newline at the end of the file please

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +	padding: 1.5em 0 0 0;
Use shorthand properties, this `padding: 1.5em 0 0;`, not `padding: 1.5em 0 0 0;`

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +blockquote:before,
Expected blank newline before this selector

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +h1, h2, h3, h4, h5, h6 {
Expected each of these on their own line:
```css
h1,
h2,
h3,
h4,
h5,
h6 {
```

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +dfn, cite, em, i {
Expected newline after each comma:
```css
dfn,
cite,
em,
i {
```

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +mark, ins {
```css
mark,
ins {
```

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +abbr, acronym {
```css
abbr, 
acronym {
```

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +code, kbd, tt, var {
```css
code, 
kbd, 
tt, 
var {
```

2016-10-15 23:04 UTC, ntwb commented on assets/css/editor-style.css
> +blockquote, q {
```css
blockquote,
q {
```

2016-10-16 16:00 UTC, laurelfulford commented on functions.php
>  add_action( 'after_setup_theme', 'twentyseventeen_setup' );
Thanks for the code review, @ntwb!

Everything should be addressed, except this one - it looks like both the functions.php and the editor-style.css files already already end with a new line in this commit. I might be misunderstanding - please let me know if this is what you meant, or something else. Thanks! 🙂

2016-10-16 19:56 UTC, merged