Link hover styling v2
WordPress/twentyseventeen pull request #341
Opened 2016-10-15 13:23 UTC by karmatosed

v3 PR for #240 fix

2016-10-15 16:49 UTC, josephfusco commented
Same comments I made in #326,
 
>Multiple comma-separated values for one property should be separated by either a space or a newline, including within rgba().
src: https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values

2016-10-15 22:50 UTC, ntwb requested changes
Added some CSS coding standards notes

2016-10-15 22:50 UTC, ntwb commented on style.css
> +	box-shadow: inset 0 -1px 0 rgba( 15, 15, 15, 1.0);
Remove the space after the opening brace and remove the trailing zero i.e this: `rgba(15, 15, 15, 1);`

2016-10-15 22:50 UTC, ntwb commented on style.css
> +	box-shadow: inset 0 -1px 0 rgba( 15, 15, 15, 1.0);
Same as above, `rgba(15, 15, 15, 1)`, not `rgba( 15, 15, 15, 1.0)`

2016-10-15 22:50 UTC, ntwb commented on style.css
> +	box-shadow: inset 0 0 0 rgba( 0, 0, 0, 0), 0 3px 0 rgba(0,0,0, 1);
No space after opening parenthesis, space after comma
 i.e `box-shadow: inset 0 0 0 rgba(0, 0, 0, 0), 0 3px 0 rgba(0, 0, 0, 1);`

2016-10-15 22:50 UTC, ntwb commented on style.css
> +	box-shadow: inset 0 0 0 rgba( 0, 0, 0, 0), 0 3px 0 rgba(0,0,0, 1);
Same as above: `box-shadow: inset 0 0 0 rgba(0, 0, 0, 0), 0 3px 0 rgba(0, 0, 0, 1);`

2016-10-17 19:44 UTC, melchoyce commented
Seeing underlines on every link now:

<img width="239" alt="screen shot 2016-10-17 at 3 43 02 pm" src="https://cloud.githubusercontent.com/assets/2846578/19452838/976259fa-9480-11e6-84d5-b74529d0608a.png">
<img width="412" alt="screen shot 2016-10-17 at 3 44 19 pm" src="https://cloud.githubusercontent.com/assets/2846578/19452839/97668c3c-9480-11e6-8941-5787c7d36e61.png">

2016-10-17 20:20 UTC, laurelfulford commented
I created a new PR - #428 - based on @karmatosed's work. It addresses the formatting changes, and limits where the hovers appear by default. Should line up with where they appeared originally.

@melchoyce - let me know if anything needs changing!

2016-10-17 21:18 UTC, josephfusco commented
Closing this in favor of #428. 👍

2016-10-17 21:18 UTC, closed without merging