Add the custom header image to the interior pages.
WordPress/twentyseventeen pull request #414
Opened 2016-10-17 03:59 UTC by ryelle

Fixes #413

I've refactored the header-image code to display the custom header on all pages, but kept the functionality of only showing a page's featured image on the front page.

I also added a new class to the body, `has-header-image`. None of the existing interior styles have been removed, as those still apply if no header is set. Instead, I'm using the new class to set the site-title color etc, instead of relying on home or `twentyseventeen-front-page`.

The JS is also tweaked slightly to account for interior menu positioning.

I did not touch the other color schemes, but they'll need to be updated too — I can do this tomorrow.

2016-10-17 20:10 UTC, ryelle commented
The color schemes shouldn't need updating since we don't change anything on top of the images. This should be ready for review 😄

2016-10-18 14:26 UTC, ntwb requested changes
Add CSS Coding Standards review

2016-10-18 14:26 UTC, ntwb commented on style.css
> +	background: -moz-linear-gradient(top,  rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 75%, rgba(0,0,0,0.3) 100%); /* FF3.6-15 */
1. Gradient should use `to top`, not `top` (A common mistake (matching outdated non-standard syntax) is to use just a side-or-corner without the preceding `to` ([src](http://stylelint.io/user-guide/rules/function-linear-gradient-no-nonstandard-direction/))

2. A single space after each comma is expected

2016-10-18 14:26 UTC, ntwb commented on style.css
> +	background: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(0,0,0,0.3) 75%,rgba(0,0,0,0.3) 100%); /* Chrome10-25,Safari5.1-6 */
1. Gradient should use `to top`, not `top` (A common mistake (matching outdated non-standard syntax) is to use just a side-or-corner without the preceding `to` ([src](http://stylelint.io/user-guide/rules/function-linear-gradient-no-nonstandard-direction/))

2. A single space after each comma is expected

2016-10-18 14:26 UTC, ntwb commented on style.css
> +	background: linear-gradient(to bottom,  rgba(0,0,0,0) 0%,rgba(0,0,0,0.3) 75%,rgba(0,0,0,0.3) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
A single space after each comma is expected

2016-10-18 14:26 UTC, ntwb commented on style.css
> +	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00000000', endColorstr='#4d000000',GradientType=0 ); /* IE6-9 */
1. A single space after each comma is expected

2. Expected double quotes, not single quotes, i.e. `"`, not `'`

2016-10-18 18:06 UTC, ryelle commented on style.css
> +	background: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(0,0,0,0.3) 75%,rgba(0,0,0,0.3) 100%); /* Chrome10-25,Safari5.1-6 */
Considering this is code copied from the existing CSS (and there's another gradient using the same syntax on `.panel-image:before`), I'd rather not make those changes here -- is there another issue or PR for CSS cleanup?

2016-10-18 18:12 UTC, ryelle commented on style.css
> +	background: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(0,0,0,0.3) 75%,rgba(0,0,0,0.3) 100%); /* Chrome10-25,Safari5.1-6 */
Just saw this was fixed with another PR, so it should be good now, right?

2016-10-19 00:11 UTC, ntwb approved these changes

2016-10-19 02:30 UTC, melchoyce commented
Being finished up in #474.

2016-10-19 02:30 UTC, closed without merging