Add base .travis.yml from Twenty Sixteen
WordPress/twentyseventeen pull request #75
Opened 2016-09-20 18:41 UTC by josephfusco

2016-09-20 18:43 UTC, josephfusco commented
Resolves #29 by introducing the travis config used for Twenty Sixteen development.

2016-09-21 00:44 UTC, ntwb commented on .travis.yml
> +# For use with the Twenty Sixteen WordPress theme
This should be "Twenty Seventeen"

2016-09-21 00:51 UTC, ntwb commented on .travis.yml
> +    - jscs .
There is no `.jscsrc` file currently in this pull request, either remove lines #69-#71 and #85-#86 or include the `.jscsrc` file from the Twenty Sixteen repo https://github.com/WordPress/twentysixteen/blob/master/.jscsrc

2016-09-21 00:51 UTC, ntwb requested changes

2016-09-21 00:53 UTC, grappler approved these changes

2016-09-21 01:50 UTC, ntwb approved these changes
Thanks @josephfusco, looks good 👍

2016-09-21 06:32 UTC, ernilambar commented on .jscsrc
> +        "js/html5.js"
May be `assets/js/html5.js` ?

2016-09-21 06:34 UTC, ernilambar commented on .travis.yml
> +    # Trunk (current version in development is 4.4)
Current development version should be 4.7

2016-09-21 14:46 UTC, ntwb approved these changes

2016-09-21 14:51 UTC, josephfusco commented
**Reminder**: once merged twentyseventeen will need to be added to https://travis-ci.org/wordpress/

2016-10-08 16:03 UTC, josephfusco commented
This would be really helpful to implement asap with the recent surge in issues and PRs.

2016-10-10 02:42 UTC, ernilambar commented
I am also not sure why this is on hold. This should have been in high priority in the review.

2016-10-10 16:45 UTC, merged