i18n Improvements
WordPress/twentyseventeen pull request #96
Opened 2016-09-26 10:18 UTC by ramiy

2016-09-26 14:59 UTC, grappler commented on comments.php
> +					_n( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'twentyseventeen' ),
This section should done like in the `_s` PR. https://github.com/Automattic/_s/pull/1012/files

2016-09-26 14:59 UTC, grappler requested changes

2016-09-26 14:59 UTC, grappler commented on inc/template-tags.php
> +			); // WPCS: XSS OK.
The comment `// WPCS: XSS OK.` needs to be on the same line as `$tags_list`

2016-09-26 14:59 UTC, grappler commented on front-page.php
> +					echo '<article class="panel-placeholder panel twentyseventeen-panel twentyseventeen-panel' . esc_attr( $twentyseventeencounter ) .'" id="panel' . esc_attr( $twentyseventeencounter ) . '"><span c
I don't think you want to remove the word "Placeholder"

2016-09-26 14:59 UTC, grappler commented on inc/template-tags.php
> +			$categories_list
The comment `// WPCS: XSS OK.` needs to be on the same line as `$categories_list`

2016-09-26 17:13 UTC, ramiy commented on inc/template-tags.php
> +			$categories_list
done.

2016-09-26 17:14 UTC, ramiy commented on inc/template-tags.php
> +			); // WPCS: XSS OK.
done.

2016-09-26 17:14 UTC, ramiy commented on front-page.php
> +					echo '<article class="panel-placeholder panel twentyseventeen-panel twentyseventeen-panel' . esc_attr( $twentyseventeencounter ) .'" id="panel' . esc_attr( $twentyseventeencounter ) . '"><span c
Reverted.

2016-09-26 17:19 UTC, ramiy commented on comments.php
> +					_n( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'twentyseventeen' ),
Separate PR.

2016-09-27 00:21 UTC, grappler commented on comments.php
> +					_n( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'twentyseventeen' ),
I am not sure what you mean.

2016-10-13 01:18 UTC, melchoyce commented
Hey @ramiy, do you know if you'll have time in the next couple of days to make updates to this PR? Just want to get an idea of where this is at. :)

2016-10-13 12:51 UTC, ramiy commented
Seems like most of my suggestion implemented. Closing the PR.

2016-10-13 12:51 UTC, closed without merging